
# This file is automatically generated, you probably don't want to edit this

twoIndependentMeansOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "twoIndependentMeansOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            ciWidth = 95,
            varEq = TRUE,
            nhst = FALSE, ...) {

            super$initialize(
                package='EstimationStats',
                name='twoIndependentMeans',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "nominal",
                    "ordinal",
                    "nominaltext"))
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)
            private$..nhst <- jmvcore::OptionBool$new(
                "nhst",
                nhst,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..varEq)
            self$.addOption(private$..nhst)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        ciWidth = function() private$..ciWidth$value,
        varEq = function() private$..varEq$value,
        nhst = function() private$..nhst$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..ciWidth = NA,
        ..varEq = NA,
        ..nhst = NA)
)

twoIndependentMeansResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        meantable = function() private$.items[["meantable"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Difference Between Two Independent Means")
            self$add(jmvcore::Table$new(
                options=options,
                name="meantable",
                title="Descriptives",
                rows=1,
                notes=list(
                    `ciNotAdjusted`="Cohen's d and it's confidence interval are not adjusted for upward bias"),
                columns=list(
                    list(
                        `name`="name[1]", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="mean[1]", 
                        `type`="number", 
                        `title`="M"),
                    list(
                        `name`="CI_low[1]", 
                        `type`="number", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="CI_high[1]", 
                        `type`="number", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="s[1]", 
                        `title`="s", 
                        `type`="number"),
                    list(
                        `name`="N[1]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="name[2]", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="mean[2]", 
                        `type`="number", 
                        `title`="M"),
                    list(
                        `name`="CI_low[2]", 
                        `type`="number", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="CI_high[2]", 
                        `type`="number", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="s[2]", 
                        `title`="s", 
                        `type`="number"),
                    list(
                        `name`="N[2]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="name[3]", 
                        `type`="text", 
                        `title`="", 
                        `content`="Difference"),
                    list(
                        `name`="mean[3]", 
                        `type`="number", 
                        `title`="M"),
                    list(
                        `name`="CI_low[3]", 
                        `type`="number", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="CI_high[3]", 
                        `type`="number", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="s[3]", 
                        `title`="s", 
                        `type`="number", 
                        `content`=""),
                    list(
                        `name`="N[3]", 
                        `title`="N", 
                        `type`="integer", 
                        `content`=""),
                    list(
                        `name`="name[4]", 
                        `type`="text", 
                        `title`="", 
                        `content`="Standardized Difference (Cohen's d)"),
                    list(
                        `name`="mean[4]", 
                        `type`="number", 
                        `title`="M", 
                        `format`="zto"),
                    list(
                        `name`="CI_low[4]", 
                        `type`="number", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval", 
                        `format`="zto"),
                    list(
                        `name`="CI_high[4]", 
                        `type`="number", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval", 
                        `format`="zto"),
                    list(
                        `name`="s[4]", 
                        `title`="s", 
                        `type`="number", 
                        `content`=""),
                    list(
                        `name`="N[4]", 
                        `title`="N", 
                        `type`="integer", 
                        `content`=""))))
            self$add(jmvcore::Html$new(
                options=options,
                name="text"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Difference Plot",
                width=600,
                height=400,
                renderFun=".plot",
                requiresData=TRUE))}))

twoIndependentMeansBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "twoIndependentMeansBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'EstimationStats',
                name = 'twoIndependentMeans',
                version = c(1,0,0),
                options = options,
                results = twoIndependentMeansResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Difference Between Two Independent Means
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param ciWidth .
#' @param varEq .
#' @param nhst .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$meantable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$meantable$asDF}
#'
#' \code{as.data.frame(results$meantable)}
#'
#' @export
twoIndependentMeans <- function(
    data,
    dep,
    group,
    ciWidth = 95,
    varEq = TRUE,
    nhst = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('twoIndependentMeans requires jmvcore to be installed (restart may be required)')

    options <- twoIndependentMeansOptions$new(
        dep = dep,
        group = group,
        ciWidth = ciWidth,
        varEq = varEq,
        nhst = nhst)

    results <- twoIndependentMeansResults$new(
        options = options)

    analysis <- twoIndependentMeansClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
