
# This file is automatically generated, you probably don't want to edit this

twoIndependentMeansOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "twoIndependentMeansOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            ciWidth = 95,
            varEq = TRUE,
            nhst = FALSE, ...) {

            super$initialize(
                package='EstimationStats',
                name='twoIndependentMeans',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)
            private$..nhst <- jmvcore::OptionBool$new(
                "nhst",
                nhst,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..varEq)
            self$.addOption(private$..nhst)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        ciWidth = function() private$..ciWidth$value,
        varEq = function() private$..varEq$value,
        nhst = function() private$..nhst$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..ciWidth = NA,
        ..varEq = NA,
        ..nhst = NA)
)

twoIndependentMeansResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        meantable = function() private$.items[["meantable"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Difference between two independent means")
            self$add(jmvcore::Table$new(
                options=options,
                name="meantable",
                title="Table of descriptives",
                rows=5,
                columns=list(
                    list(
                        `name`="Group", 
                        `type`="text"),
                    list(
                        `name`="M", 
                        `type`="number"),
                    list(
                        `name`="CI_low", 
                        `type`="number"),
                    list(
                        `name`="CI_high", 
                        `type`="number"),
                    list(
                        `name`="s", 
                        `type`="number"),
                    list(
                        `name`="N", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Difference Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

twoIndependentMeansBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "twoIndependentMeansBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'EstimationStats',
                name = 'twoIndependentMeans',
                version = c(1,0,0),
                options = options,
                results = twoIndependentMeansResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Difference between two independent means
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param ciWidth .
#' @param varEq .
#' @param nhst .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$meantable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$meantable$asDF}
#'
#' \code{as.data.frame(results$meantable)}
#'
#' @export
twoIndependentMeans <- function(
    data,
    dep,
    group,
    ciWidth = 95,
    varEq = TRUE,
    nhst = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('twoIndependentMeans requires jmvcore to be installed (restart may be required)')

    options <- twoIndependentMeansOptions$new(
        dep = dep,
        group = group,
        ciWidth = ciWidth,
        varEq = varEq,
        nhst = nhst)

    results <- twoIndependentMeansResults$new(
        options = options)

    analysis <- twoIndependentMeansClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
